'use client';

import { useMemo } from 'react';
import { type SchemeMeta, useSchemeMeta } from './scheme-meta';

export type BrandUiSkinStyle = Record<`--${string}`, string>;

export interface BrandUiSkin {
    brand: SchemeMeta['brand'];
    mode: SchemeMeta['mode'];
    style: BrandUiSkinStyle;
}

const SUPERBET_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #070708 0%, #32090b 44%, #070708 100%)',
    '--brand-topbar-border': 'rgba(194, 30, 28, 0.5)',
    '--brand-topbar-before-bg': '#070708',
    '--brand-nav-item-text': '#f5f5f5',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--brand-nav-active-bg': '#c21e1c',
    '--brand-nav-active-hover-bg': '#d72825',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#c21e1c',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(255, 255, 255, 0.08)',

    '--brand-sidebar-bg': '#101213',
    '--brand-sidebar-border': '#2b2f31',
    '--brand-sidebar-header-bg': '#181a1b',
    '--brand-right-rail-bg': '#070708',
    '--brand-right-rail-button-bg': '#181a1b',
    '--brand-right-rail-button-border': '#34393b',

    '--interactive-row-text': '#b8bec1',
    '--interactive-row-icon': '#b8bec1',
    '--interactive-row-hover-bg': '#222628',
    '--interactive-row-hover-text': '#f5f5f5',
    '--interactive-row-hover-icon': '#c21e1c',
    '--interactive-row-active-bg': '#321415',
    '--interactive-row-active-text': '#f5f5f5',
    '--interactive-row-active-icon': '#e3312f',
    '--interactive-active-rail-bg': '#c21e1c',
    '--interactive-active-rail-shadow': '0 0 8px rgba(194, 30, 28, 0.55)',

    '--brand-match-card-bg': '#181a1b',
    '--brand-match-card-border': '#34393b',
    '--brand-match-card-hover-bg': '#202426',
    '--brand-match-card-shadow': '0 18px 34px -24px rgba(0, 0, 0, 0.82)',
    '--brand-match-card-radius': '10px',
    '--brand-match-divider': '#2f3436',
    '--brand-match-muted': '#a0a6a9',
    '--brand-match-team-text': '#f5f5f5',
    '--brand-match-league-text': '#f5f5f5',

    '--brand-odds-bg': '#272b2d',
    '--brand-odds-border': '#34393b',
    '--brand-odds-hover-bg': '#34393b',
    '--brand-odds-hover-border': '#4d5558',
    '--brand-odds-name': '#d6dadc',
    '--brand-odds-value': '#ffffff',
    '--brand-odds-radius': '5px',
    '--brand-odds-short-height': '32px',
    '--brand-odds-selected-bg': '#c21e1c',
    '--brand-odds-selected-hover-bg': '#d72825',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#181a1b',
    '--brand-mobile-sport-nav-border': '#34393b',
    '--brand-mobile-sport-nav-hover-bg': '#222628',
    '--brand-mobile-sport-nav-icon-bg': '#321415',
    '--brand-mobile-sport-nav-icon': '#e3312f',
    '--brand-mobile-sport-nav-text': '#f5f5f5',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(194, 30, 28, 0.72)',
};

const GTB_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #fff7f7 0%, #ffffff 42%, #fff7f7 100%)',
    '--brand-topbar-border': '#f1d5d6',
    '--brand-topbar-before-bg': '#fff7f7',
    '--brand-nav-item-text': '#2a303c',
    '--brand-nav-item-hover-bg': '#fff0f0',
    '--brand-nav-active-bg': '#e80104',
    '--brand-nav-active-hover-bg': '#c70003',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#e80104',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#fff0f0',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#e2e5ea',
    '--brand-sidebar-header-bg': '#f5f6f8',
    '--brand-right-rail-bg': '#f5f6f8',
    '--brand-right-rail-button-bg': '#ffffff',
    '--brand-right-rail-button-border': '#e2e5ea',

    '--interactive-row-text': '#495266',
    '--interactive-row-icon': '#6d7d98',
    '--interactive-row-hover-bg': '#fff0f0',
    '--interactive-row-hover-text': '#2a303c',
    '--interactive-row-hover-icon': '#e80104',
    '--interactive-row-active-bg': '#ffdddd',
    '--interactive-row-active-text': '#2a303c',
    '--interactive-row-active-icon': '#e80104',
    '--interactive-active-rail-bg': '#e80104',
    '--interactive-active-rail-shadow': 'none',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#e2e5ea',
    '--brand-match-card-hover-bg': '#fff7f7',
    '--brand-match-card-shadow': '0 1px 2px rgba(46, 46, 46, 0.08)',
    '--brand-match-divider': '#e2e5ea',
    '--brand-match-muted': '#6d7d98',
    '--brand-match-team-text': '#2a303c',
    '--brand-match-league-text': '#495266',

    '--brand-odds-bg': '#f5f6f8',
    '--brand-odds-border': '#e2e5ea',
    '--brand-odds-hover-bg': '#fff0f0',
    '--brand-odds-hover-border': '#e80104',
    '--brand-odds-name': '#6d7d98',
    '--brand-odds-value': '#2a303c',
    '--brand-odds-selected-bg': '#e80104',
    '--brand-odds-selected-hover-bg': '#c70003',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#e2e5ea',
    '--brand-mobile-sport-nav-hover-bg': '#fff0f0',
    '--brand-mobile-sport-nav-icon-bg': '#ffdddd',
    '--brand-mobile-sport-nav-icon': '#e80104',
    '--brand-mobile-sport-nav-text': '#2a303c',
    '--brand-mobile-sport-nav-shadow': '0 10px 18px -16px rgba(232, 1, 4, 0.32)',
};

const SUPERBET_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #ffffff 0%, #fff4f4 44%, #ffffff 100%)',
    '--brand-topbar-border': '#e7d5d5',
    '--brand-topbar-before-bg': '#f6f7f9',
    '--brand-nav-item-text': '#303947',
    '--brand-nav-item-hover-bg': '#f0f2f6',
    '--brand-nav-active-bg': '#c21e1c',
    '--brand-nav-active-hover-bg': '#a91817',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#c21e1c',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#fff1f2',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#dbe1ea',
    '--brand-sidebar-header-bg': '#f6f7f9',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#f6f7f9',
    '--brand-right-rail-button-border': '#dbe1ea',

    '--interactive-row-text': '#5c6879',
    '--interactive-row-icon': '#5c6879',
    '--interactive-row-hover-bg': '#fff1f2',
    '--interactive-row-hover-text': '#151923',
    '--interactive-row-hover-icon': '#c21e1c',
    '--interactive-row-active-bg': '#ffe7e6',
    '--interactive-row-active-text': '#151923',
    '--interactive-row-active-icon': '#c21e1c',
    '--interactive-active-rail-bg': '#c21e1c',
    '--interactive-active-rail-shadow': '0 0 8px rgba(194, 30, 28, 0.35)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#e2e7ef',
    '--brand-match-card-hover-bg': '#fff7f7',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(14, 17, 24, 0.24)',
    '--brand-match-card-radius': '10px',
    '--brand-match-divider': '#e2e7ef',
    '--brand-match-muted': '#7c8898',
    '--brand-match-team-text': '#151923',
    '--brand-match-league-text': '#303947',

    '--brand-odds-bg': '#f6f7f9',
    '--brand-odds-border': '#dbe1ea',
    '--brand-odds-hover-bg': '#fff0f0',
    '--brand-odds-hover-border': '#c21e1c',
    '--brand-odds-name': '#5c6879',
    '--brand-odds-value': '#151923',
    '--brand-odds-radius': '5px',
    '--brand-odds-short-height': '32px',
    '--brand-odds-selected-bg': '#c21e1c',
    '--brand-odds-selected-hover-bg': '#a91817',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#dbe1ea',
    '--brand-mobile-sport-nav-hover-bg': '#fff1f2',
    '--brand-mobile-sport-nav-icon-bg': '#ffe6e9',
    '--brand-mobile-sport-nav-icon': '#e60012',
    '--brand-mobile-sport-nav-text': '#151923',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(14, 17, 24, 0.28)',
};

const BETANO_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #071040 0%, #101a58 52%, #071040 100%)',
    '--brand-topbar-border': 'rgba(255, 90, 31, 0.54)',
    '--brand-topbar-before-bg': '#071040',
    '--brand-nav-item-text': '#f4f6fb',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--brand-nav-active-bg': 'transparent',
    '--brand-nav-active-hover-bg': 'rgba(255, 90, 31, 0.12)',
    '--brand-nav-active-text': '#ff7a40',
    '--brand-nav-active-underline': '#ff5a1f',
    '--brand-nav-live-badge-bg': '#ff5a1f',
    '--brand-nav-live-badge-text': '#071040',
    '--brand-logo-hover-bg': 'rgba(255, 90, 31, 0.12)',

    '--brand-sidebar-bg': '#0a1038',
    '--brand-sidebar-border': '#222c68',
    '--brand-sidebar-header-bg': '#101a58',
    '--brand-right-rail-bg': '#071040',
    '--brand-right-rail-button-bg': '#101a58',
    '--brand-right-rail-button-border': '#25306d',

    '--interactive-row-text': '#c6cbea',
    '--interactive-row-icon': '#c6cbea',
    '--interactive-row-hover-bg': '#17205b',
    '--interactive-row-hover-text': '#ffffff',
    '--interactive-row-hover-icon': '#ff7a40',
    '--interactive-row-active-bg': '#1d2660',
    '--interactive-row-active-text': '#ffffff',
    '--interactive-row-active-icon': '#ff7a40',
    '--interactive-active-rail-bg': '#ff5a1f',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 90, 31, 0.55)',

    '--brand-match-card-bg': '#18191f',
    '--brand-match-card-border': '#2f3542',
    '--brand-match-card-hover-bg': '#1f2129',
    '--brand-match-card-shadow': 'none',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#2f3542',
    '--brand-match-muted': '#9aa4b8',
    '--brand-match-team-text': '#f4f6fb',
    '--brand-match-league-text': '#d4d9e8',

    '--brand-odds-bg': '#242731',
    '--brand-odds-border': '#3b4252',
    '--brand-odds-hover-bg': '#2b303b',
    '--brand-odds-hover-border': '#5b6475',
    '--brand-odds-name': '#d4d9e8',
    '--brand-odds-value': '#74b852',
    '--brand-odds-radius': '8px',
    '--brand-odds-short-height': '36px',
    '--brand-odds-selected-bg': '#ff3d00',
    '--brand-odds-selected-hover-bg': '#ff5a1f',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#101a58',
    '--brand-mobile-sport-nav-border': '#27306a',
    '--brand-mobile-sport-nav-hover-bg': '#17205b',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(255, 90, 31, 0.16)',
    '--brand-mobile-sport-nav-icon': '#ff7a40',
    '--brand-mobile-sport-nav-text': '#ffffff',
    '--brand-mobile-sport-nav-shadow': '0 12px 24px -18px rgba(7, 16, 64, 0.88)',
};

const BETANO_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    ...BETANO_UI_STYLE,
    '--brand-topbar-bg': 'linear-gradient(90deg, #ff3d00 0%, #ff5a1f 52%, #ff3d00 100%)',
    '--brand-topbar-border': '#d93400',
    '--brand-topbar-before-bg': '#ff3d00',
    '--brand-nav-item-text': '#ffffff',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.16)',
    '--brand-nav-active-bg': '#111b34',
    '--brand-nav-active-hover-bg': '#1b2743',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': '#111b34',
    '--brand-nav-live-badge-bg': '#111b34',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(17, 27, 52, 0.14)',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#eadfd9',
    '--brand-sidebar-header-bg': '#fff8f4',
    '--brand-right-rail-bg': '#fff8f4',
    '--brand-right-rail-button-bg': '#ffffff',
    '--brand-right-rail-button-border': '#eadfd9',

    '--interactive-row-text': '#303852',
    '--interactive-row-icon': '#5b647e',
    '--interactive-row-hover-bg': '#fff3ed',
    '--interactive-row-hover-text': '#101426',
    '--interactive-row-hover-icon': '#ff5a1f',
    '--interactive-row-active-bg': '#fff0ea',
    '--interactive-row-active-text': '#101426',
    '--interactive-row-active-icon': '#ff5a1f',
    '--interactive-active-rail-bg': '#ff5a1f',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 90, 31, 0.35)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#e2e8f8',
    '--brand-match-card-hover-bg': '#f7f9fc',
    '--brand-match-card-shadow': 'none',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#e2e8f8',
    '--brand-match-muted': '#60739f',
    '--brand-match-team-text': '#151923',
    '--brand-match-league-text': '#1c2026',

    '--brand-odds-bg': '#f7f9fc',
    '--brand-odds-border': '#e2e8f8',
    '--brand-odds-hover-bg': '#eef3fb',
    '--brand-odds-hover-border': '#cbd6ec',
    '--brand-odds-name': '#151923',
    '--brand-odds-value': '#3a7824',
    '--brand-odds-radius': '8px',
    '--brand-odds-short-height': '36px',
    '--brand-odds-selected-bg': '#ff3d00',
    '--brand-odds-selected-hover-bg': '#e13700',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#eadfd9',
    '--brand-mobile-sport-nav-hover-bg': '#fff8f4',
    '--brand-mobile-sport-nav-icon-bg': '#fff0e8',
    '--brand-mobile-sport-nav-icon': '#ff3d00',
    '--brand-mobile-sport-nav-text': '#111b34',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(17, 27, 52, 0.28)',
};

const BETBUS_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #050505 0%, #101010 52%, #050505 100%)',
    '--brand-topbar-border': 'rgba(250, 67, 78, 0.38)',
    '--brand-topbar-before-bg': '#050505',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#252525',
    '--brand-nav-active-bg': '#fa434e',
    '--brand-nav-active-hover-bg': '#fa434e',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#fa434e',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#252525',

    '--brand-sidebar-bg': '#121212',
    '--brand-sidebar-border': '#313131',
    '--brand-sidebar-header-bg': '#1e1e1e',
    '--brand-right-rail-bg': '#010101',
    '--brand-right-rail-button-bg': '#121212',
    '--brand-right-rail-button-border': '#313131',

    '--brand-match-card-bg': '#252525',
    '--brand-match-card-border': '#313131',
    '--brand-match-card-hover-bg': '#2f2f2f',
    '--brand-match-card-shadow': 'none',
    '--brand-match-divider': '#313131',
    '--brand-match-muted': '#878787',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#1f1f1f',
    '--brand-odds-border': '#444444',
    '--brand-odds-hover-bg': '#321016',
    '--brand-odds-hover-border': '#fa434e',
    '--brand-odds-name': '#c3c3c3',
    '--brand-odds-value': '#f0c289',
    '--brand-odds-selected-bg': '#fa434e',
    '--brand-odds-selected-hover-bg': '#ff5b65',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#252525',
    '--brand-mobile-sport-nav-border': '#3a3a3a',
    '--brand-mobile-sport-nav-hover-bg': '#2f2f2f',
    '--brand-mobile-sport-nav-icon-bg': '#321016',
    '--brand-mobile-sport-nav-icon': '#fa434e',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const BETBUS_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    ...BETBUS_UI_STYLE,
    '--brand-topbar-bg': 'linear-gradient(90deg, #ffffff 0%, #f4f8f6 52%, #ffffff 100%)',
    '--brand-topbar-border': '#d8e2dd',
    '--brand-topbar-before-bg': '#ffffff',
    '--brand-nav-item-text': '#17251f',
    '--brand-nav-item-hover-bg': '#ecf5f0',
    '--brand-nav-active-bg': '#169c63',
    '--brand-nav-active-hover-bg': '#169c63',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-live-badge-bg': '#169c63',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#ecf5f0',
    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#d8e2dd',
    '--brand-sidebar-header-bg': '#f8fbf9',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#f8fbf9',
    '--brand-right-rail-button-border': '#d8e2dd',
    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#d8e2dd',
    '--brand-match-card-hover-bg': '#f8fbf9',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(16, 37, 28, 0.24)',
    '--brand-match-divider': '#dce8e2',
    '--brand-match-muted': '#7b8b84',
    '--brand-match-team-text': '#17251f',
    '--brand-match-league-text': '#33443c',
    '--brand-odds-bg': '#f8fbf9',
    '--brand-odds-border': '#d8e2dd',
    '--brand-odds-hover-bg': 'rgba(22, 156, 99, 0.12)',
    '--brand-odds-hover-border': '#169c63',
    '--brand-odds-name': '#5e7068',
    '--brand-odds-value': '#17251f',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #33d488, #169c63)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #4ade99, #16a66b)',
    '--brand-odds-selected-text': '#062014',
    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#d8e2dd',
    '--brand-mobile-sport-nav-hover-bg': '#ecf5f0',
    '--brand-mobile-sport-nav-icon-bg': '#e7f5ef',
    '--brand-mobile-sport-nav-icon': '#169c63',
    '--brand-mobile-sport-nav-text': '#17251f',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const MATCH_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #0f0f0f 0%, #161616 42%, #0f0f0f 100%)',
    '--brand-topbar-border': 'rgba(38, 192, 122, 0.42)',
    '--brand-topbar-before-bg': '#0f0f0f',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#1e1e1e',
    '--brand-nav-active-bg': '#26c07a',
    '--brand-nav-active-hover-bg': '#33d488',
    '--brand-nav-active-text': '#07130d',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#26c07a',
    '--brand-nav-live-badge-text': '#07130d',
    '--brand-logo-hover-bg': '#1e1e1e',

    '--brand-sidebar-bg': '#161616',
    '--brand-sidebar-border': '#313131',
    '--brand-sidebar-header-bg': '#1e1e1e',
    '--brand-right-rail-bg': '#0f0f0f',
    '--brand-right-rail-button-bg': '#1e1e1e',
    '--brand-right-rail-button-border': '#313131',

    '--interactive-row-text': '#a6a6a6',
    '--interactive-row-icon': '#a6a6a6',
    '--interactive-row-hover-bg': '#1e1e1e',
    '--interactive-row-hover-text': '#f2f2f2',
    '--interactive-row-hover-icon': '#26c07a',
    '--interactive-row-active-bg': '#2b2b2b',
    '--interactive-row-active-text': '#f2f2f2',
    '--interactive-row-active-icon': '#26c07a',
    '--interactive-active-rail-bg': '#26c07a',
    '--interactive-active-rail-shadow': '0 0 8px rgba(38, 192, 122, 0.65)',

    '--brand-match-card-bg': '#1e1e1e',
    '--brand-match-card-border': '#313131',
    '--brand-match-card-hover-bg': '#242424',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.75)',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#313131',
    '--brand-match-muted': '#8c8c8c',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#2b2b2b',
    '--brand-odds-border': '#414141',
    '--brand-odds-radius': '9px',
    '--brand-odds-hover-bg': 'rgba(38, 192, 122, 0.13)',
    '--brand-odds-hover-border': '#26c07a',
    '--brand-odds-name': '#c8c8c8',
    '--brand-odds-value': '#33d488',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #33d488, #1b9e61)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #3fe094, #26c07a)',
    '--brand-odds-selected-text': '#07130d',
    '--brand-odds-short-height': '36px',

    '--brand-mobile-sport-nav-bg': '#1e1e1e',
    '--brand-mobile-sport-nav-border': '#313131',
    '--brand-mobile-sport-nav-hover-bg': '#242424',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(38, 192, 122, 0.13)',
    '--brand-mobile-sport-nav-icon': '#26c07a',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const MATCH_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'rgba(255, 255, 255, 0.82)',
    '--brand-topbar-border': '#d3dbe6',
    '--brand-topbar-before-bg': '#ffffff',
    '--brand-nav-item-text': '#0e1726',
    '--brand-nav-item-hover-bg': 'rgba(15, 156, 97, 0.14)',
    '--brand-nav-active-bg': '#0f9c61',
    '--brand-nav-active-hover-bg': '#0a784c',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#e23b3b',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#dde4ed',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#d3dbe6',
    '--brand-sidebar-header-bg': '#f4f7fb',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#dde4ed',
    '--brand-right-rail-button-border': '#bcc7d6',

    '--interactive-row-text': '#4b5564',
    '--interactive-row-icon': '#6b7585',
    '--interactive-row-hover-bg': '#ffffff',
    '--interactive-row-hover-text': '#0e1726',
    '--interactive-row-hover-icon': '#0f9c61',
    '--interactive-row-active-bg': '#dde4ed',
    '--interactive-row-active-text': '#0e1726',
    '--interactive-row-active-icon': '#0f9c61',
    '--interactive-active-rail-bg': '#0f9c61',
    '--interactive-active-rail-shadow': '0 0 8px rgba(15, 156, 97, 0.45)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#d3dbe6',
    '--brand-match-card-hover-bg': '#ffffff',
    '--brand-match-card-shadow': 'none',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#d3dbe6',
    '--brand-match-muted': '#6b7585',
    '--brand-match-team-text': '#0e1726',
    '--brand-match-league-text': '#4b5564',

    '--brand-odds-bg': '#eef2f8',
    '--brand-odds-border': '#d3dbe6',
    '--brand-odds-radius': '9px',
    '--brand-odds-hover-bg': 'rgba(15, 156, 97, 0.14)',
    '--brand-odds-hover-border': '#0f9c61',
    '--brand-odds-name': '#4b5564',
    '--brand-odds-value': '#0e1726',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #15a96c, #0a784c)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #21b878, #0f9c61)',
    '--brand-odds-selected-text': '#ffffff',
    '--brand-odds-short-height': '36px',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#d3dbe6',
    '--brand-mobile-sport-nav-hover-bg': '#e9eef6',
    '--brand-mobile-sport-nav-icon-bg': '#dde4ed',
    '--brand-mobile-sport-nav-icon': '#0f9c61',
    '--brand-mobile-sport-nav-text': '#0e1726',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(15, 23, 38, 0.32)',
};

/* MATCH 配色变体 · 薄荷绿：深蓝灰底 + 薄荷绿主色。 */
const MATCH_MINT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #0b0e13 0%, #10141b 42%, #0b0e13 100%)',
    '--brand-topbar-border': 'rgba(31, 224, 160, 0.42)',
    '--brand-topbar-before-bg': '#0b0e13',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#161b24',
    '--brand-nav-active-bg': '#1fe0a0',
    '--brand-nav-active-hover-bg': '#4ff0bc',
    '--brand-nav-active-text': '#07130d',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#1fe0a0',
    '--brand-nav-live-badge-text': '#07130d',
    '--brand-logo-hover-bg': '#161b24',

    '--brand-sidebar-bg': '#10141b',
    '--brand-sidebar-border': '#283040',
    '--brand-sidebar-header-bg': '#161b24',
    '--brand-right-rail-bg': '#0b0e13',
    '--brand-right-rail-button-bg': '#161b24',
    '--brand-right-rail-button-border': '#283040',

    '--interactive-row-text': '#a6a6a6',
    '--interactive-row-icon': '#a6a6a6',
    '--interactive-row-hover-bg': '#161b24',
    '--interactive-row-hover-text': '#f2f2f2',
    '--interactive-row-hover-icon': '#1fe0a0',
    '--interactive-row-active-bg': '#212834',
    '--interactive-row-active-text': '#f2f2f2',
    '--interactive-row-active-icon': '#1fe0a0',
    '--interactive-active-rail-bg': '#1fe0a0',
    '--interactive-active-rail-shadow': '0 0 8px rgba(31, 224, 160, 0.65)',

    '--brand-match-card-bg': '#161b24',
    '--brand-match-card-border': '#283040',
    '--brand-match-card-hover-bg': '#212834',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.75)',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#283040',
    '--brand-match-muted': '#8c8c8c',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#212834',
    '--brand-odds-border': '#38424f',
    '--brand-odds-radius': '9px',
    '--brand-odds-hover-bg': 'rgba(31, 224, 160, 0.13)',
    '--brand-odds-hover-border': '#1fe0a0',
    '--brand-odds-name': '#c8c8c8',
    '--brand-odds-value': '#4ff0bc',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #4ff0bc, #15b07e)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #6af5cc, #1fe0a0)',
    '--brand-odds-selected-text': '#07130d',
    '--brand-odds-short-height': '36px',

    '--brand-mobile-sport-nav-bg': '#161b24',
    '--brand-mobile-sport-nav-border': '#283040',
    '--brand-mobile-sport-nav-hover-bg': '#212834',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(31, 224, 160, 0.13)',
    '--brand-mobile-sport-nav-icon': '#1fe0a0',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

/* MATCH 配色变体 · 亮黑绿：沿用黑底，主色换成更亮的荧光绿。 */
const MATCH_BRIGHT_UI_STYLE: BrandUiSkinStyle = {
    ...MATCH_UI_STYLE,
    '--brand-topbar-border': 'rgba(59, 214, 59, 0.42)',
    '--brand-nav-active-bg': '#3bd63b',
    '--brand-nav-active-hover-bg': '#5fe85f',
    '--brand-nav-live-badge-bg': '#3bd63b',
    '--interactive-row-hover-icon': '#3bd63b',
    '--interactive-row-active-icon': '#3bd63b',
    '--interactive-active-rail-bg': '#3bd63b',
    '--interactive-active-rail-shadow': '0 0 8px rgba(59, 214, 59, 0.65)',
    '--brand-odds-hover-bg': 'rgba(59, 214, 59, 0.13)',
    '--brand-odds-hover-border': '#3bd63b',
    '--brand-odds-value': '#5fe85f',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #5fe85f, #25a82e)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #7af07a, #3bd63b)',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(59, 214, 59, 0.13)',
    '--brand-mobile-sport-nav-icon': '#3bd63b',
};

/* MATCH 配色变体 · 黑红：沿用黑底，主色换成红色，赔率数值保留绿色（涨=绿）。 */
const MATCH_RED_UI_STYLE: BrandUiSkinStyle = {
    ...MATCH_UI_STYLE,
    '--brand-topbar-border': 'rgba(230, 32, 43, 0.42)',
    '--brand-nav-active-bg': '#e6202b',
    '--brand-nav-active-hover-bg': '#ff3b46',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-live-badge-bg': '#e6202b',
    '--brand-nav-live-badge-text': '#ffffff',
    '--interactive-row-hover-icon': '#ff3b46',
    '--interactive-row-active-icon': '#ff3b46',
    '--interactive-active-rail-bg': '#e6202b',
    '--interactive-active-rail-shadow': '0 0 8px rgba(230, 32, 43, 0.65)',
    '--brand-odds-hover-bg': 'rgba(230, 32, 43, 0.13)',
    '--brand-odds-hover-border': '#e6202b',
    '--brand-odds-value': '#33d488',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ff3b46, #b3151f)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ff5560, #e6202b)',
    '--brand-odds-selected-text': '#ffffff',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(230, 32, 43, 0.13)',
    '--brand-mobile-sport-nav-icon': '#ff3b46',
};

/* MATCH 配色变体 · 深蓝红：深蓝底 + 红色主色，赔率数值保留绿色（涨=绿）。 */
const MATCH_NAVY_RED_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #0b0f18 0%, #0f1421 42%, #0b0f18 100%)',
    '--brand-topbar-border': 'rgba(230, 32, 43, 0.42)',
    '--brand-topbar-before-bg': '#0b0f18',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#161d2c',
    '--brand-nav-active-bg': '#e6202b',
    '--brand-nav-active-hover-bg': '#ff3b46',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#e6202b',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#161d2c',

    '--brand-sidebar-bg': '#0f1421',
    '--brand-sidebar-border': '#283449',
    '--brand-sidebar-header-bg': '#161d2c',
    '--brand-right-rail-bg': '#0b0f18',
    '--brand-right-rail-button-bg': '#161d2c',
    '--brand-right-rail-button-border': '#283449',

    '--interactive-row-text': '#a6a6a6',
    '--interactive-row-icon': '#a6a6a6',
    '--interactive-row-hover-bg': '#161d2c',
    '--interactive-row-hover-text': '#f2f2f2',
    '--interactive-row-hover-icon': '#ff3b46',
    '--interactive-row-active-bg': '#202a3c',
    '--interactive-row-active-text': '#f2f2f2',
    '--interactive-row-active-icon': '#ff3b46',
    '--interactive-active-rail-bg': '#e6202b',
    '--interactive-active-rail-shadow': '0 0 8px rgba(230, 32, 43, 0.65)',

    '--brand-match-card-bg': '#161d2c',
    '--brand-match-card-border': '#283449',
    '--brand-match-card-hover-bg': '#202a3c',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.75)',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#283449',
    '--brand-match-muted': '#8c8c8c',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#202a3c',
    '--brand-odds-border': '#38465f',
    '--brand-odds-radius': '9px',
    '--brand-odds-hover-bg': 'rgba(230, 32, 43, 0.13)',
    '--brand-odds-hover-border': '#e6202b',
    '--brand-odds-name': '#c8c8c8',
    '--brand-odds-value': '#33d488',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ff3b46, #b3151f)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ff5560, #e6202b)',
    '--brand-odds-selected-text': '#ffffff',
    '--brand-odds-short-height': '36px',

    '--brand-mobile-sport-nav-bg': '#161d2c',
    '--brand-mobile-sport-nav-border': '#283449',
    '--brand-mobile-sport-nav-hover-bg': '#202a3c',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(230, 32, 43, 0.13)',
    '--brand-mobile-sport-nav-icon': '#ff3b46',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

/* MATCH 配色变体 · 深蓝黄：深蓝底 + 黄色主色，赔率数值保留绿色（涨=绿）。 */
const MATCH_NAVY_YELLOW_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #0b0f18 0%, #0f1421 42%, #0b0f18 100%)',
    '--brand-topbar-border': 'rgba(255, 210, 26, 0.42)',
    '--brand-topbar-before-bg': '#0b0f18',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#161d2c',
    '--brand-nav-active-bg': '#ffd21a',
    '--brand-nav-active-hover-bg': '#ffe04d',
    '--brand-nav-active-text': '#241c00',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#ffd21a',
    '--brand-nav-live-badge-text': '#241c00',
    '--brand-logo-hover-bg': '#161d2c',

    '--brand-sidebar-bg': '#0f1421',
    '--brand-sidebar-border': '#283449',
    '--brand-sidebar-header-bg': '#161d2c',
    '--brand-right-rail-bg': '#0b0f18',
    '--brand-right-rail-button-bg': '#161d2c',
    '--brand-right-rail-button-border': '#283449',

    '--interactive-row-text': '#a6a6a6',
    '--interactive-row-icon': '#a6a6a6',
    '--interactive-row-hover-bg': '#161d2c',
    '--interactive-row-hover-text': '#f2f2f2',
    '--interactive-row-hover-icon': '#ffd21a',
    '--interactive-row-active-bg': '#202a3c',
    '--interactive-row-active-text': '#f2f2f2',
    '--interactive-row-active-icon': '#ffd21a',
    '--interactive-active-rail-bg': '#ffd21a',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 210, 26, 0.65)',

    '--brand-match-card-bg': '#161d2c',
    '--brand-match-card-border': '#283449',
    '--brand-match-card-hover-bg': '#202a3c',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.75)',
    '--brand-match-card-radius': '12px',
    '--brand-match-divider': '#283449',
    '--brand-match-muted': '#8c8c8c',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#202a3c',
    '--brand-odds-border': '#38465f',
    '--brand-odds-radius': '9px',
    '--brand-odds-hover-bg': 'rgba(255, 210, 26, 0.13)',
    '--brand-odds-hover-border': '#ffd21a',
    '--brand-odds-name': '#c8c8c8',
    '--brand-odds-value': '#33d488',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ffe04d, #d6a800)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ffe874, #ffd21a)',
    '--brand-odds-selected-text': '#241c00',
    '--brand-odds-short-height': '36px',

    '--brand-mobile-sport-nav-bg': '#161d2c',
    '--brand-mobile-sport-nav-border': '#283449',
    '--brand-mobile-sport-nav-hover-bg': '#202a3c',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(255, 210, 26, 0.13)',
    '--brand-mobile-sport-nav-icon': '#ffd21a',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

/* MATCH 深色变体按 scheme 名分发（gtb 式 scheme 级特例，因 skin 默认仅按 brand×mode 取值）。 */
const MATCH_DARK_SKIN_BY_SCHEME: Record<string, BrandUiSkinStyle> = {
    match: MATCH_UI_STYLE,
    'match-mint': MATCH_MINT_UI_STYLE,
    'match-bright': MATCH_BRIGHT_UI_STYLE,
    'match-red': MATCH_RED_UI_STYLE,
    'match-navy-red': MATCH_NAVY_RED_UI_STYLE,
    'match-navy-yellow': MATCH_NAVY_YELLOW_UI_STYLE,
};

/* iOS26 液态玻璃 · 暗：紫粉渐变 + 半透明外壳（配合 glass.css 的 backdrop-filter 折射）。 */
const GLASS_DARK_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg':
        'linear-gradient(90deg, oklch(0.195 0.028 290 / 0.62) 0%, oklch(0.21 0.034 300 / 0.62) 44%, oklch(0.195 0.028 290 / 0.62) 100%)',
    '--brand-topbar-border': 'rgba(196, 181, 253, 0.22)',
    '--brand-topbar-before-bg': 'oklch(0.195 0.028 290 / 0.62)',
    '--brand-nav-item-text': '#ddd8f0',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--brand-nav-active-bg': 'linear-gradient(135deg, #8b5cf6, #ec4899)',
    '--brand-nav-active-hover-bg': 'linear-gradient(135deg, #7c3aed, #db2777)',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#ec4899',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(255, 255, 255, 0.08)',

    '--brand-sidebar-bg': 'oklch(0.195 0.028 290 / 0.6)',
    '--brand-sidebar-border': 'rgba(196, 181, 253, 0.16)',
    '--brand-sidebar-header-bg': 'oklch(0.225 0.03 290 / 0.62)',
    '--brand-right-rail-bg': 'oklch(0.185 0.026 290 / 0.6)',
    '--brand-right-rail-button-bg': 'oklch(0.265 0.032 290 / 0.7)',
    '--brand-right-rail-button-border': 'rgba(196, 181, 253, 0.2)',

    '--interactive-row-text': '#c4bce0',
    '--interactive-row-icon': '#c4bce0',
    '--interactive-row-hover-bg': 'rgba(139, 92, 246, 0.16)',
    '--interactive-row-hover-text': '#f6f4fe',
    '--interactive-row-hover-icon': '#c084fc',
    '--interactive-row-active-bg': 'rgba(139, 92, 246, 0.26)',
    '--interactive-row-active-text': '#f6f4fe',
    '--interactive-row-active-icon': '#e879f9',
    '--interactive-active-rail-bg': 'linear-gradient(180deg, #8b5cf6, #ec4899)',
    '--interactive-active-rail-shadow': '0 0 10px rgba(168, 85, 247, 0.6)',

    '--brand-match-card-bg': 'oklch(0.245 0.03 290 / 0.74)',
    '--brand-match-card-border': 'oklch(0.72 0.035 290 / 0.2)',
    '--brand-match-card-hover-bg': 'oklch(0.3 0.032 290 / 0.78)',
    '--brand-match-card-shadow': '0 16px 40px -24px rgba(76, 29, 149, 0.6)',
    '--brand-match-card-radius': '18px',
    '--brand-match-divider': 'rgba(196, 181, 253, 0.14)',
    '--brand-match-muted': '#9b8fc4',
    '--brand-match-team-text': '#f6f4fe',
    '--brand-match-league-text': '#ddd8f0',

    '--brand-odds-bg': 'oklch(0.3 0.03 290 / 0.72)',
    '--brand-odds-border': 'rgba(196, 181, 253, 0.18)',
    '--brand-odds-radius': '14px',
    '--brand-odds-hover-bg': 'oklch(0.4 0.08 300 / 0.5)',
    '--brand-odds-hover-border': '#a855f7',
    '--brand-odds-name': '#c4bce0',
    '--brand-odds-value': '#f6f4fe',
    '--brand-odds-short-height': '36px',
    '--brand-odds-selected-bg': 'linear-gradient(135deg, #8b5cf6, #ec4899)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(135deg, #7c3aed, #db2777)',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': 'oklch(0.245 0.03 290 / 0.72)',
    '--brand-mobile-sport-nav-border': 'rgba(196, 181, 253, 0.16)',
    '--brand-mobile-sport-nav-hover-bg': 'oklch(0.3 0.032 290 / 0.76)',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(139, 92, 246, 0.2)',
    '--brand-mobile-sport-nav-icon': '#c084fc',
    '--brand-mobile-sport-nav-text': '#f6f4fe',
    '--brand-mobile-sport-nav-shadow': '0 12px 24px -18px rgba(40, 16, 70, 0.7)',
};

/* iOS26 液态玻璃 · 亮：紫粉渐变 + 半透明白外壳。17 个 match-card/odds 必填键全部显式列出（theme:check 闸门）。 */
const GLASS_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'rgba(255, 255, 255, 0.6)',
    '--brand-topbar-border': 'rgba(147, 51, 234, 0.18)',
    '--brand-topbar-before-bg': 'rgba(255, 255, 255, 0.6)',
    '--brand-nav-item-text': '#1b1335',
    '--brand-nav-item-hover-bg': 'rgba(147, 51, 234, 0.1)',
    '--brand-nav-active-bg': 'linear-gradient(135deg, #9333ea, #db2777)',
    '--brand-nav-active-hover-bg': 'linear-gradient(135deg, #7e22ce, #be185d)',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#db2777',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(147, 51, 234, 0.1)',

    '--brand-sidebar-bg': 'rgba(255, 255, 255, 0.55)',
    '--brand-sidebar-border': 'rgba(147, 51, 234, 0.14)',
    '--brand-sidebar-header-bg': 'rgba(245, 243, 255, 0.6)',
    '--brand-right-rail-bg': 'rgba(255, 255, 255, 0.55)',
    '--brand-right-rail-button-bg': 'rgba(255, 255, 255, 0.6)',
    '--brand-right-rail-button-border': 'rgba(147, 51, 234, 0.16)',

    '--interactive-row-text': '#534b73',
    '--interactive-row-icon': '#6b6390',
    '--interactive-row-hover-bg': 'rgba(255, 255, 255, 0.7)',
    '--interactive-row-hover-text': '#1b1335',
    '--interactive-row-hover-icon': '#9333ea',
    '--interactive-row-active-bg': 'rgba(147, 51, 234, 0.16)',
    '--interactive-row-active-text': '#1b1335',
    '--interactive-row-active-icon': '#9333ea',
    '--interactive-active-rail-bg': 'linear-gradient(180deg, #9333ea, #db2777)',
    '--interactive-active-rail-shadow': '0 0 8px rgba(147, 51, 234, 0.45)',

    '--brand-match-card-bg': 'rgba(255, 255, 255, 0.6)',
    '--brand-match-card-border': 'rgba(255, 255, 255, 0.6)',
    '--brand-match-card-hover-bg': 'rgba(255, 255, 255, 0.72)',
    '--brand-match-card-shadow': '0 12px 32px -20px rgba(124, 58, 237, 0.35)',
    '--brand-match-card-radius': '18px',
    '--brand-match-divider': 'rgba(147, 51, 234, 0.12)',
    '--brand-match-muted': '#6b6390',
    '--brand-match-team-text': '#1b1335',
    '--brand-match-league-text': '#534b73',

    '--brand-odds-bg': 'rgba(255, 255, 255, 0.55)',
    '--brand-odds-border': 'rgba(147, 51, 234, 0.16)',
    '--brand-odds-radius': '14px',
    '--brand-odds-hover-bg': 'rgba(147, 51, 234, 0.12)',
    '--brand-odds-hover-border': '#9333ea',
    '--brand-odds-name': '#534b73',
    '--brand-odds-value': '#1b1335',
    '--brand-odds-short-height': '36px',
    '--brand-odds-selected-bg': 'linear-gradient(135deg, #9333ea, #db2777)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(135deg, #7e22ce, #be185d)',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': 'rgba(255, 255, 255, 0.6)',
    '--brand-mobile-sport-nav-border': 'rgba(147, 51, 234, 0.14)',
    '--brand-mobile-sport-nav-hover-bg': 'rgba(255, 255, 255, 0.72)',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(147, 51, 234, 0.12)',
    '--brand-mobile-sport-nav-icon': '#9333ea',
    '--brand-mobile-sport-nav-text': '#1b1335',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(124, 58, 237, 0.28)',
};

export const getBrandUiSkin = (schemeMeta: SchemeMeta): BrandUiSkin => {
    if (schemeMeta.scheme === 'gtb') {
        return {
            brand: 'superbet',
            mode: schemeMeta.mode,
            style: GTB_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'betano') {
        return {
            brand: 'betano',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? BETANO_LIGHT_UI_STYLE : BETANO_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'betbus') {
        return {
            brand: 'betbus',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? BETBUS_LIGHT_UI_STYLE : BETBUS_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'match') {
        if (schemeMeta.mode === 'light') {
            return { brand: 'match', mode: 'light', style: MATCH_LIGHT_UI_STYLE };
        }

        return {
            brand: 'match',
            mode: 'dark',
            style: MATCH_DARK_SKIN_BY_SCHEME[schemeMeta.scheme] ?? MATCH_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'glass') {
        return {
            brand: 'glass',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? GLASS_LIGHT_UI_STYLE : GLASS_DARK_UI_STYLE,
        };
    }

    return {
        brand: 'superbet',
        mode: schemeMeta.mode,
        style: schemeMeta.mode === 'light' ? SUPERBET_LIGHT_UI_STYLE : SUPERBET_UI_STYLE,
    };
};

export const useBrandUiSkin = (): BrandUiSkin => {
    const schemeMeta = useSchemeMeta();

    return useMemo(() => getBrandUiSkin(schemeMeta), [schemeMeta]);
};
