'use client';

import { useMemo } from 'react';
import { type SchemeMeta, useSchemeMeta } from './scheme-meta';

export type BrandUiSkinStyle = Record<`--${string}`, string>;

export interface BrandUiSkin {
    brand: SchemeMeta['brand'];
    mode: SchemeMeta['mode'];
    style: BrandUiSkinStyle;
}

const SUPERBET_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #07080c 0%, #1d070b 44%, #07080c 100%)',
    '--brand-topbar-border': 'rgba(255, 31, 50, 0.42)',
    '--brand-topbar-before-bg': '#07080c',
    '--brand-nav-item-text': '#f4f6f9',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--brand-nav-active-bg': '#ff1f32',
    '--brand-nav-active-hover-bg': '#ff1f32',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#ff1f32',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(255, 255, 255, 0.08)',

    '--brand-sidebar-bg': '#0d0f16',
    '--brand-sidebar-border': '#282d3a',
    '--brand-sidebar-header-bg': '#171a23',
    '--brand-right-rail-bg': '#07080c',
    '--brand-right-rail-button-bg': '#11141c',
    '--brand-right-rail-button-border': '#282d3a',

    '--interactive-row-text': '#b3bac6',
    '--interactive-row-icon': '#b3bac6',
    '--interactive-row-hover-bg': '#202431',
    '--interactive-row-hover-text': '#f4f6f9',
    '--interactive-row-hover-icon': '#ff1f32',
    '--interactive-row-active-bg': '#2a1820',
    '--interactive-row-active-text': '#f4f6f9',
    '--interactive-row-active-icon': '#ff1f32',
    '--interactive-active-rail-bg': '#ff1f32',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 31, 50, 0.55)',

    '--brand-match-card-bg': '#171a23',
    '--brand-match-card-border': '#282d3a',
    '--brand-match-card-hover-bg': '#1d212c',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.78)',
    '--brand-match-divider': '#282d3a',
    '--brand-match-muted': '#858d9b',
    '--brand-match-team-text': '#f4f6f9',
    '--brand-match-league-text': '#f4f6f9',

    '--brand-odds-bg': '#202431',
    '--brand-odds-border': '#3b4252',
    '--brand-odds-hover-bg': 'rgba(255, 31, 50, 0.14)',
    '--brand-odds-hover-border': '#ff1f32',
    '--brand-odds-name': '#d5d9e1',
    '--brand-odds-value': '#ffcc33',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ff4a59, #d90014)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ff6170, #ff1f32)',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#171a23',
    '--brand-mobile-sport-nav-border': '#323746',
    '--brand-mobile-sport-nav-hover-bg': '#202431',
    '--brand-mobile-sport-nav-icon-bg': '#2a1820',
    '--brand-mobile-sport-nav-icon': '#ff1f32',
    '--brand-mobile-sport-nav-text': '#f4f6f9',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(255, 31, 50, 0.72)',
};

const GTB_UI_STYLE: BrandUiSkinStyle = {
    ...SUPERBET_UI_STYLE,
    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#dbe1ea',
    '--brand-match-card-hover-bg': '#fff9fa',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(14, 17, 24, 0.24)',
    '--brand-match-divider': '#e2e7ef',
    '--brand-match-muted': '#7c8898',
    '--brand-match-team-text': '#151923',
    '--brand-match-league-text': '#303947',

    '--brand-odds-bg': '#f6f7f9',
    '--brand-odds-border': '#dbe1ea',
    '--brand-odds-hover-bg': 'rgba(230, 0, 18, 0.1)',
    '--brand-odds-hover-border': '#e60012',
    '--brand-odds-name': '#5c6879',
    '--brand-odds-value': '#151923',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ff3345, #e60012)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ff4a59, #bf0010)',
    '--brand-odds-selected-text': '#ffffff',
};

const SUPERBET_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #ffffff 0%, #fff4f5 44%, #ffffff 100%)',
    '--brand-topbar-border': '#dbe1ea',
    '--brand-topbar-before-bg': '#f6f7f9',
    '--brand-nav-item-text': '#303947',
    '--brand-nav-item-hover-bg': '#f0f2f6',
    '--brand-nav-active-bg': '#e60012',
    '--brand-nav-active-hover-bg': '#bf0010',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#e60012',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#fff1f2',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#dbe1ea',
    '--brand-sidebar-header-bg': '#f6f7f9',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#f6f7f9',
    '--brand-right-rail-button-border': '#dbe1ea',

    '--interactive-row-text': '#5c6879',
    '--interactive-row-icon': '#5c6879',
    '--interactive-row-hover-bg': '#fff1f2',
    '--interactive-row-hover-text': '#151923',
    '--interactive-row-hover-icon': '#e60012',
    '--interactive-row-active-bg': '#ffe6e9',
    '--interactive-row-active-text': '#151923',
    '--interactive-row-active-icon': '#e60012',
    '--interactive-active-rail-bg': '#e60012',
    '--interactive-active-rail-shadow': '0 0 8px rgba(230, 0, 18, 0.35)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#dbe1ea',
    '--brand-match-card-hover-bg': '#fff9fa',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(14, 17, 24, 0.24)',
    '--brand-match-divider': '#e2e7ef',
    '--brand-match-muted': '#7c8898',
    '--brand-match-team-text': '#151923',
    '--brand-match-league-text': '#303947',

    '--brand-odds-bg': '#f6f7f9',
    '--brand-odds-border': '#dbe1ea',
    '--brand-odds-hover-bg': 'rgba(230, 0, 18, 0.1)',
    '--brand-odds-hover-border': '#e60012',
    '--brand-odds-name': '#5c6879',
    '--brand-odds-value': '#151923',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #ff3345, #e60012)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #ff4a59, #bf0010)',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#dbe1ea',
    '--brand-mobile-sport-nav-hover-bg': '#fff1f2',
    '--brand-mobile-sport-nav-icon-bg': '#ffe6e9',
    '--brand-mobile-sport-nav-icon': '#e60012',
    '--brand-mobile-sport-nav-text': '#151923',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(14, 17, 24, 0.28)',
};

const BETANO_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #071040 0%, #101a58 52%, #071040 100%)',
    '--brand-topbar-border': 'rgba(255, 90, 31, 0.54)',
    '--brand-topbar-before-bg': '#071040',
    '--brand-nav-item-text': '#f4f6fb',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--brand-nav-active-bg': 'transparent',
    '--brand-nav-active-hover-bg': 'rgba(255, 90, 31, 0.12)',
    '--brand-nav-active-text': '#ff7a40',
    '--brand-nav-active-underline': '#ff5a1f',
    '--brand-nav-live-badge-bg': '#ff5a1f',
    '--brand-nav-live-badge-text': '#071040',
    '--brand-logo-hover-bg': 'rgba(255, 90, 31, 0.12)',

    '--brand-sidebar-bg': '#0a1038',
    '--brand-sidebar-border': '#222c68',
    '--brand-sidebar-header-bg': '#101a58',
    '--brand-right-rail-bg': '#071040',
    '--brand-right-rail-button-bg': '#101a58',
    '--brand-right-rail-button-border': '#25306d',

    '--interactive-row-text': '#c6cbea',
    '--interactive-row-icon': '#c6cbea',
    '--interactive-row-hover-bg': '#17205b',
    '--interactive-row-hover-text': '#ffffff',
    '--interactive-row-hover-icon': '#ff7a40',
    '--interactive-row-active-bg': '#1d2660',
    '--interactive-row-active-text': '#ffffff',
    '--interactive-row-active-icon': '#ff7a40',
    '--interactive-active-rail-bg': '#ff5a1f',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 90, 31, 0.55)',

    '--brand-match-card-bg': '#12194a',
    '--brand-match-card-border': '#27306a',
    '--brand-match-card-hover-bg': '#17205b',
    '--brand-match-card-shadow': '0 16px 34px -24px rgba(0, 0, 0, 0.8)',
    '--brand-match-divider': '#27306a',
    '--brand-match-muted': '#9ea7d0',
    '--brand-match-team-text': '#ffffff',
    '--brand-match-league-text': '#ffffff',

    '--brand-odds-bg': '#1d2660',
    '--brand-odds-border': '#334080',
    '--brand-odds-hover-bg': 'rgba(49, 216, 147, 0.14)',
    '--brand-odds-hover-border': '#31d893',
    '--brand-odds-name': '#c9cff0',
    '--brand-odds-value': '#31d893',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #31d893, #00a067)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #42e5a3, #00b572)',
    '--brand-odds-selected-text': '#071040',

    '--brand-mobile-sport-nav-bg': '#101a58',
    '--brand-mobile-sport-nav-border': '#27306a',
    '--brand-mobile-sport-nav-hover-bg': '#17205b',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(255, 90, 31, 0.16)',
    '--brand-mobile-sport-nav-icon': '#ff7a40',
    '--brand-mobile-sport-nav-text': '#ffffff',
    '--brand-mobile-sport-nav-shadow': '0 12px 24px -18px rgba(7, 16, 64, 0.88)',
};

const BETANO_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    ...BETANO_UI_STYLE,
    '--brand-topbar-bg': 'linear-gradient(90deg, #ff3d00 0%, #ff5a1f 52%, #ff3d00 100%)',
    '--brand-topbar-border': '#d93400',
    '--brand-topbar-before-bg': '#ff3d00',
    '--brand-nav-item-text': '#ffffff',
    '--brand-nav-item-hover-bg': 'rgba(255, 255, 255, 0.16)',
    '--brand-nav-active-bg': '#111b34',
    '--brand-nav-active-hover-bg': '#1b2743',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': '#111b34',
    '--brand-nav-live-badge-bg': '#111b34',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': 'rgba(17, 27, 52, 0.14)',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#eadfd9',
    '--brand-sidebar-header-bg': '#fff8f4',
    '--brand-right-rail-bg': '#fff8f4',
    '--brand-right-rail-button-bg': '#ffffff',
    '--brand-right-rail-button-border': '#eadfd9',

    '--interactive-row-text': '#303852',
    '--interactive-row-icon': '#5b647e',
    '--interactive-row-hover-bg': '#fff3ed',
    '--interactive-row-hover-text': '#101426',
    '--interactive-row-hover-icon': '#ff5a1f',
    '--interactive-row-active-bg': '#fff0ea',
    '--interactive-row-active-text': '#101426',
    '--interactive-row-active-icon': '#ff5a1f',
    '--interactive-active-rail-bg': '#ff5a1f',
    '--interactive-active-rail-shadow': '0 0 8px rgba(255, 90, 31, 0.35)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#dfe4ec',
    '--brand-match-card-hover-bg': '#f7f9fb',
    '--brand-match-card-shadow': '0 10px 24px -20px rgba(17, 27, 52, 0.22)',
    '--brand-match-divider': '#e5e9ef',
    '--brand-match-muted': '#6e7688',
    '--brand-match-team-text': '#111b34',
    '--brand-match-league-text': '#303852',

    '--brand-odds-bg': '#f3f5f8',
    '--brand-odds-border': '#dfe4ec',
    '--brand-odds-hover-bg': '#edf8f3',
    '--brand-odds-hover-border': '#00a067',
    '--brand-odds-name': '#5b647e',
    '--brand-odds-value': '#008f5c',
    '--brand-odds-selected-bg': '#00a067',
    '--brand-odds-selected-hover-bg': '#008f5c',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#eadfd9',
    '--brand-mobile-sport-nav-hover-bg': '#fff8f4',
    '--brand-mobile-sport-nav-icon-bg': '#fff0e8',
    '--brand-mobile-sport-nav-icon': '#ff3d00',
    '--brand-mobile-sport-nav-text': '#111b34',
    '--brand-mobile-sport-nav-shadow': '0 12px 22px -18px rgba(17, 27, 52, 0.28)',
};

const BETBUS_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #050505 0%, #101010 52%, #050505 100%)',
    '--brand-topbar-border': 'rgba(250, 67, 78, 0.38)',
    '--brand-topbar-before-bg': '#050505',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#252525',
    '--brand-nav-active-bg': '#fa434e',
    '--brand-nav-active-hover-bg': '#fa434e',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#fa434e',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#252525',

    '--brand-sidebar-bg': '#121212',
    '--brand-sidebar-border': '#313131',
    '--brand-sidebar-header-bg': '#1e1e1e',
    '--brand-right-rail-bg': '#010101',
    '--brand-right-rail-button-bg': '#121212',
    '--brand-right-rail-button-border': '#313131',

    '--brand-match-card-bg': '#252525',
    '--brand-match-card-border': '#313131',
    '--brand-match-card-hover-bg': '#2f2f2f',
    '--brand-match-card-shadow': 'none',
    '--brand-match-divider': '#313131',
    '--brand-match-muted': '#878787',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#1f1f1f',
    '--brand-odds-border': '#444444',
    '--brand-odds-hover-bg': '#321016',
    '--brand-odds-hover-border': '#fa434e',
    '--brand-odds-name': '#c3c3c3',
    '--brand-odds-value': '#f0c289',
    '--brand-odds-selected-bg': '#fa434e',
    '--brand-odds-selected-hover-bg': '#ff5b65',
    '--brand-odds-selected-text': '#ffffff',

    '--brand-mobile-sport-nav-bg': '#252525',
    '--brand-mobile-sport-nav-border': '#3a3a3a',
    '--brand-mobile-sport-nav-hover-bg': '#2f2f2f',
    '--brand-mobile-sport-nav-icon-bg': '#321016',
    '--brand-mobile-sport-nav-icon': '#fa434e',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const BETBUS_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    ...BETBUS_UI_STYLE,
    '--brand-topbar-bg': 'linear-gradient(90deg, #ffffff 0%, #f4f8f6 52%, #ffffff 100%)',
    '--brand-topbar-border': '#d8e2dd',
    '--brand-topbar-before-bg': '#ffffff',
    '--brand-nav-item-text': '#17251f',
    '--brand-nav-item-hover-bg': '#ecf5f0',
    '--brand-nav-active-bg': '#169c63',
    '--brand-nav-active-hover-bg': '#169c63',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-live-badge-bg': '#169c63',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#ecf5f0',
    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#d8e2dd',
    '--brand-sidebar-header-bg': '#f8fbf9',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#f8fbf9',
    '--brand-right-rail-button-border': '#d8e2dd',
    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#d8e2dd',
    '--brand-match-card-hover-bg': '#f8fbf9',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(16, 37, 28, 0.24)',
    '--brand-match-divider': '#dce8e2',
    '--brand-match-muted': '#7b8b84',
    '--brand-match-team-text': '#17251f',
    '--brand-match-league-text': '#33443c',
    '--brand-odds-bg': '#f8fbf9',
    '--brand-odds-border': '#d8e2dd',
    '--brand-odds-hover-bg': 'rgba(22, 156, 99, 0.12)',
    '--brand-odds-hover-border': '#169c63',
    '--brand-odds-name': '#5e7068',
    '--brand-odds-value': '#17251f',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #33d488, #169c63)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #4ade99, #16a66b)',
    '--brand-odds-selected-text': '#062014',
    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#d8e2dd',
    '--brand-mobile-sport-nav-hover-bg': '#ecf5f0',
    '--brand-mobile-sport-nav-icon-bg': '#e7f5ef',
    '--brand-mobile-sport-nav-icon': '#169c63',
    '--brand-mobile-sport-nav-text': '#17251f',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const MATCH_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #0f0f0f 0%, #161616 42%, #0f0f0f 100%)',
    '--brand-topbar-border': 'rgba(38, 192, 122, 0.42)',
    '--brand-topbar-before-bg': '#0f0f0f',
    '--brand-nav-item-text': '#f2f2f2',
    '--brand-nav-item-hover-bg': '#1e1e1e',
    '--brand-nav-active-bg': '#26c07a',
    '--brand-nav-active-hover-bg': '#33d488',
    '--brand-nav-active-text': '#07130d',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#26c07a',
    '--brand-nav-live-badge-text': '#07130d',
    '--brand-logo-hover-bg': '#1e1e1e',

    '--brand-sidebar-bg': '#161616',
    '--brand-sidebar-border': '#313131',
    '--brand-sidebar-header-bg': '#1e1e1e',
    '--brand-right-rail-bg': '#0f0f0f',
    '--brand-right-rail-button-bg': '#1e1e1e',
    '--brand-right-rail-button-border': '#313131',

    '--interactive-row-text': '#a6a6a6',
    '--interactive-row-icon': '#a6a6a6',
    '--interactive-row-hover-bg': '#1e1e1e',
    '--interactive-row-hover-text': '#f2f2f2',
    '--interactive-row-hover-icon': '#26c07a',
    '--interactive-row-active-bg': '#2b2b2b',
    '--interactive-row-active-text': '#f2f2f2',
    '--interactive-row-active-icon': '#26c07a',
    '--interactive-active-rail-bg': '#26c07a',
    '--interactive-active-rail-shadow': '0 0 8px rgba(38, 192, 122, 0.65)',

    '--brand-match-card-bg': '#1e1e1e',
    '--brand-match-card-border': '#313131',
    '--brand-match-card-hover-bg': '#242424',
    '--brand-match-card-shadow': '0 16px 32px -22px rgba(0, 0, 0, 0.75)',
    '--brand-match-divider': '#313131',
    '--brand-match-muted': '#8c8c8c',
    '--brand-match-team-text': '#f2f2f2',
    '--brand-match-league-text': '#f2f2f2',

    '--brand-odds-bg': '#2b2b2b',
    '--brand-odds-border': '#414141',
    '--brand-odds-hover-bg': 'rgba(38, 192, 122, 0.13)',
    '--brand-odds-hover-border': '#26c07a',
    '--brand-odds-name': '#c8c8c8',
    '--brand-odds-value': '#ffce4d',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #33d488, #1b9e61)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #3fe094, #26c07a)',
    '--brand-odds-selected-text': '#07130d',

    '--brand-mobile-sport-nav-bg': '#1e1e1e',
    '--brand-mobile-sport-nav-border': '#313131',
    '--brand-mobile-sport-nav-hover-bg': '#242424',
    '--brand-mobile-sport-nav-icon-bg': 'rgba(38, 192, 122, 0.13)',
    '--brand-mobile-sport-nav-icon': '#26c07a',
    '--brand-mobile-sport-nav-text': '#f2f2f2',
    '--brand-mobile-sport-nav-shadow': 'none',
};

const MATCH_LIGHT_UI_STYLE: BrandUiSkinStyle = {
    '--brand-topbar-bg': 'linear-gradient(90deg, #ffffff 0%, #f4f8f6 44%, #ffffff 100%)',
    '--brand-topbar-border': '#d8e2dd',
    '--brand-topbar-before-bg': '#ffffff',
    '--brand-nav-item-text': '#17251f',
    '--brand-nav-item-hover-bg': '#ecf5f0',
    '--brand-nav-active-bg': '#169c63',
    '--brand-nav-active-hover-bg': '#0f7f50',
    '--brand-nav-active-text': '#ffffff',
    '--brand-nav-active-underline': 'transparent',
    '--brand-nav-live-badge-bg': '#169c63',
    '--brand-nav-live-badge-text': '#ffffff',
    '--brand-logo-hover-bg': '#ecf5f0',

    '--brand-sidebar-bg': '#ffffff',
    '--brand-sidebar-border': '#d8e2dd',
    '--brand-sidebar-header-bg': '#f8fbf9',
    '--brand-right-rail-bg': '#ffffff',
    '--brand-right-rail-button-bg': '#f8fbf9',
    '--brand-right-rail-button-border': '#d8e2dd',

    '--interactive-row-text': '#5e7068',
    '--interactive-row-icon': '#5e7068',
    '--interactive-row-hover-bg': '#ecf5f0',
    '--interactive-row-hover-text': '#17251f',
    '--interactive-row-hover-icon': '#169c63',
    '--interactive-row-active-bg': '#dff3ea',
    '--interactive-row-active-text': '#17251f',
    '--interactive-row-active-icon': '#169c63',
    '--interactive-active-rail-bg': '#169c63',
    '--interactive-active-rail-shadow': '0 0 8px rgba(22, 156, 99, 0.35)',

    '--brand-match-card-bg': '#ffffff',
    '--brand-match-card-border': '#d8e2dd',
    '--brand-match-card-hover-bg': '#f8fbf9',
    '--brand-match-card-shadow': '0 12px 28px -22px rgba(16, 37, 28, 0.24)',
    '--brand-match-divider': '#dce8e2',
    '--brand-match-muted': '#7b8b84',
    '--brand-match-team-text': '#17251f',
    '--brand-match-league-text': '#33443c',

    '--brand-odds-bg': '#f8fbf9',
    '--brand-odds-border': '#d8e2dd',
    '--brand-odds-hover-bg': 'rgba(22, 156, 99, 0.12)',
    '--brand-odds-hover-border': '#169c63',
    '--brand-odds-name': '#5e7068',
    '--brand-odds-value': '#17251f',
    '--brand-odds-selected-bg': 'linear-gradient(140deg, #33d488, #169c63)',
    '--brand-odds-selected-hover-bg': 'linear-gradient(140deg, #4ade99, #16a66b)',
    '--brand-odds-selected-text': '#062014',

    '--brand-mobile-sport-nav-bg': '#ffffff',
    '--brand-mobile-sport-nav-border': '#d8e2dd',
    '--brand-mobile-sport-nav-hover-bg': '#ecf5f0',
    '--brand-mobile-sport-nav-icon-bg': '#e7f5ef',
    '--brand-mobile-sport-nav-icon': '#169c63',
    '--brand-mobile-sport-nav-text': '#17251f',
    '--brand-mobile-sport-nav-shadow': 'none',
};

export const getBrandUiSkin = (schemeMeta: SchemeMeta): BrandUiSkin => {
    if (schemeMeta.scheme === 'gtb') {
        return {
            brand: 'superbet',
            mode: schemeMeta.mode,
            style: GTB_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'betano') {
        return {
            brand: 'betano',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? BETANO_LIGHT_UI_STYLE : BETANO_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'betbus') {
        return {
            brand: 'betbus',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? BETBUS_LIGHT_UI_STYLE : BETBUS_UI_STYLE,
        };
    }

    if (schemeMeta.brand === 'match') {
        return {
            brand: 'match',
            mode: schemeMeta.mode,
            style: schemeMeta.mode === 'light' ? MATCH_LIGHT_UI_STYLE : MATCH_UI_STYLE,
        };
    }

    return {
        brand: 'superbet',
        mode: schemeMeta.mode,
        style: schemeMeta.mode === 'light' ? SUPERBET_LIGHT_UI_STYLE : SUPERBET_UI_STYLE,
    };
};

export const useBrandUiSkin = (): BrandUiSkin => {
    const schemeMeta = useSchemeMeta();

    return useMemo(() => getBrandUiSkin(schemeMeta), [schemeMeta]);
};
