/** clabe 银行 */
export const CLABE_BANKS: { label: string; id: string }[] = [
    { label: 'BBVA México', id: '012' },
    { label: 'Santander', id: '014' },
    { label: 'Banorte', id: '072' },
    { label: 'HSBC México', id: '021' },
    { label: 'Scotiabank', id: '044' },
    { label: 'Banco Azteca', id: '127' },
    { label: 'Bancoppel', id: '137' },
    { label: 'Inbursa', id: '036' },
    { label: 'Banco del Bajío', id: '030' },
    { label: 'Banamex', id: '002' },
    { label: 'Banco Nacional de Comercio Exterior', id: '006' },
    { label: 'Banobras', id: '009' },
    { label: 'Banco Nacional del Ejército', id: '019' },
    { label: 'IXE / Banorte', id: '032' },
    { label: 'Interacciones', id: '037' },
    { label: 'Mifel', id: '042' },
    { label: 'Banregio', id: '058' },
    { label: 'Invex', id: '059' },
    { label: 'Bansi', id: '060' },
    { label: 'Afirme', id: '062' },
    { label: 'Bankaool', id: '102' },
    { label: 'American Express Bank', id: '103' },
    { label: 'Bank of America México', id: '106' },
    { label: 'MUFG Bank México', id: '108' },
    { label: 'JP Morgan México', id: '110' },
    { label: 'Banco Ve por Más', id: '112' },
    { label: 'Banco Monex', id: '113' },
    { label: 'Accendo Banco (CLOSED)', id: '114' },
    { label: 'ING Bank México', id: '116' },
    { label: 'ABC Capital', id: '124' },
    { label: 'Credit Suisse México', id: '126' },
    { label: 'Autofin', id: '128' },
    { label: 'Barclays México', id: '129' },
    { label: 'Compartamos Banco', id: '130' },
    { label: 'Banco Famsa (CLOSED)', id: '131' },
    { label: 'Multiva', id: '132' },
    { label: 'Actinver', id: '133' },
    { label: 'Banco Walmart (CLOSED)', id: '134' },
    { label: 'Nacional Financiera', id: '135' },
    { label: 'Intercam', id: '136' },
    { label: 'ABC Capital (duplicate)', id: '138' },
    { label: 'UBS México', id: '139' },
    { label: 'Consubanco', id: '140' },
    { label: 'Volaris Bank', id: '141' },
    { label: 'CIBanco', id: '143' },
    { label: 'Banco Base', id: '145' },
    { label: 'Banco del Bienestar', id: '166' },
    { label: 'Hipotecaria Federal', id: '168' },
    { label: 'SPEI (Generic)', id: '600' },
    { label: 'SPEI Secondary', id: '601' },
    { label: 'SPEI Extended', id: '602' },
    { label: 'STP', id: '646' },
    { label: 'Transfer', id: '647' },
    { label: 'CoDi / Banxico', id: '648' },
    { label: 'Fintech Platform', id: '649' },
    { label: 'Payment Aggregator', id: '650' },
    { label: 'Digital Wallet', id: '651' },
    { label: 'Electronic Payment System', id: '652' },
    { label: 'Virtual Bank', id: '653' },
    { label: 'Fintech Clearing', id: '654' },
    { label: 'Digital Account', id: '655' },
    { label: 'Klar', id: '656' },
    { label: 'Fintech Wallet', id: '657' },
    { label: 'Digital Finance', id: '658' },
    { label: 'Albo', id: '659' },
    { label: 'NeoBank', id: '660' },
    { label: 'Digital Payments', id: '661' },
    { label: 'Open Banking', id: '662' },
    { label: 'Fintech API Bank', id: '663' },
    { label: 'Mobile Bank', id: '664' },
    { label: 'Cloud Bank', id: '665' },
    { label: 'Digital Wallet MX', id: '666' },
    { label: 'Payment Gateway', id: '667' },
    { label: 'Fintech Services', id: '668' },
    { label: 'Virtual Accounts', id: '669' },
    { label: 'Clip', id: '670' },
    { label: 'Fintech Transfer', id: '671' },
    { label: 'Wallet Services', id: '672' },
    { label: 'Payment Hub', id: '673' },
    { label: 'Digital Bank MX', id: '674' },
    { label: 'Aggregator Bank', id: '675' },
    { label: 'Fintech Core', id: '676' },
    { label: 'Wallet MX', id: '677' },
    { label: 'Virtual Banking', id: '678' },
    { label: 'Payment Services', id: '679' },
    { label: 'Neo Payments', id: '680' },
    { label: 'Mercado Pago', id: '701' },
    { label: 'PayPal México', id: '702' },
    { label: 'Stripe México', id: '703' },
    { label: 'Square México', id: '704' },
    { label: 'Digital Wallet LATAM', id: '705' },
    { label: 'Payment Processor', id: '706' },
    { label: 'Online Banking MX', id: '707' },
    { label: 'Wallet LATAM', id: '708' },
    { label: 'Aggregator LATAM', id: '709' },
    { label: 'Fintech LATAM', id: '710' },
];
